---
source-template:
- required:
  - name: name
    fieldtype: text
    required: true
  - name: metapath
    fieldtype: text
    required: true
    value: "Sources"
  - name: namespace
    fieldtype: text
    required: true
    value: "we1sv2.0"
  - name: title
    fieldtype: text
    required: true
- optional:
  - name: id
    fieldtype: text
  - name: _id
    fieldtype: text
  - name: description
    fieldtype: textarea
  - name: version
    fieldtype: text
  - name: shortTitle
    fieldtype: text
  - name: label
    fieldtype: text
  - name: notes
    fieldtype: textarea
  - name: keywords
    fieldtype: text
    placeholder: Separate multiple keywords with commas.
  - name: image
    fieldtype: text
  - name: webpage
    fieldtype: text
  - name: publisher
    fieldtype: text
  - name: authors
    fieldtype: textarea
  - name: date
    fieldtype: textarea
    placeholder: List each date on a separate line. Date ranges should separate start and end dates with commas. Valid formats are YYYY-MM-DD and YYYY-MM-DDTHH:MM:SS.
  - name: edition
    fieldtype: text
  - name: contentType
    fieldtype: text
  - name: country
    fieldtype: select
    default: US
  - name: language
    fieldtype: select
    default: eng
  - name: citation
    fieldtype: text